version: "3.7"
services:
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=automate
      - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
  app:
    build: app
    restart: always
    volumes:
      - ./app/src:/code
    secrets:
      - db-password
    networks:
      - backend
      - frontend
    ports:
      - 5678:5678
  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  backend:
  frontend: