version: "3.7"
services:
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=automate
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - backend
  app:
    build: app
    restart: always
    networks:
      - backend
      - frontend
  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
networks:
  backend:
  frontend: